all: single-account load-account issue-page

load-account:
	go build load-account.go

single-account:
	go build single-account.go

issue-page:
	go build issue-page.go

clean:
	rm single-account load-account issue-page
